apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argocd 
spec:
  project: golang
  source:
    repoURL: https://github.com/jzlyy/user-service.git
    path: kubernetes/overlays/production
    targetRevision: HEAD
    kustomize:
      images:
        - name: crpi-5dxngct78yux2w9r.cn-chengdu.personal.cr.aliyuncs.com/product_123/user-service
          newTag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      selfHeal: true  # 自动修复漂移
      prune: true     # 删除不再使用的资源
    syncOptions:
      - CreateNamespace=true  # 如果命名空间不存在则创建
      - ApplyOutOfSyncOnly=true
