apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golang-app
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/jzlyy/user-service.git
    path: kubernetes/overlays/production
    targetRevision: HEAD
    kustomize:
      images:
        - name: docker.io/zfc123/golang-app
          newTag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      selfHeal: true  # 自动修复漂移
      prune: true     # 删除不再使用的资源
    syncOptions:
      - CreateNamespace=true  # 如果命名空间不存在则创建
      - ApplyOutOfSyncOnly=true
