apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: backend
data:
  GIN_MODE: "release"
  DB_HOST: "rm-cn-rp64e1o1h00024.rwlb.cn-chengdu.rds.aliyuncs.com"
  DB_PORT: "3306"
  DB_NAME: "ecommerce"
  REDIS_HOST: "redis-headless.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  RedisDB: "0"
  RABBITMQ_HOST: "rabbitmq-headless.rabbitmq.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_DELAY: "5000"
  CACHE_TTL: "30"
  NACOS_ADDRESSES: "mse-96d22c713-nacos-ans.mse.aliyuncs.com"
  NACOS_NAMESPACE: "product"
  NACOS_GROUP: "DEFAULT_GROUP"
  NACOS_CLUSTER: "DEFAULT"
  SERVICE_NAME: "user-service"
  ServicePort: "8080"
  FROM_EMAIL: "wwyxhqc1@jzlyy.xyz"
  SENDGRID_EU_ACCOUNT: "false"
