apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: backend
data:
  DB_HOST: "mysql-headless.mysql.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "ecommerce"
  RABBITMQ_HOST: "rabbitmq-headless.rabbitmq.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  ETCD_ADDRESS: ""
  SERVICE_NAME: "user-service"
  ServicePort: "8080"
  FROM_EMAIL: "wwyxhqc1@jzlyy.xyz"
  SENDGRID_EU_ACCOUNT: "false"
