apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service
  namespace: backend
data:
  DB_USER: "root"
  DB_HOST: "localhost"
  DB_PORT: "3306"
  DB_NAME: "ecommerce"
  FROM_EMAIL: "wwyxhqc1@jzlyy.xyz"
  SENDGRID_EU_ACCOUNT: "false"
  RABBITMQ_HOST: "172.168.20.30"
  RABBITMQ_PORT: "5672"
