apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service 
  namespace: backend
  labels:
    app: user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
      annotations:
        argocd-image-updater.argoproj.io/image-list: app=docker.io/zfc123/golang-app
        argocd-image-updater.argoproj.io/app.update-strategy: latest
    spec:
      containers:
        - name: user-service
          image: docker.io/zfc123/golang-app:latest
          ports:
            - containerPort: 8080
              name: user-backend
          volumeMounts:
            - name: user-configmap
              mountPath: "/etc/configmap"
              readOnly: true
            - name: user-secret 
              mountPath: "/etc/secrets"
              readOnly: true
          resources:
            requests:
              cpu: 1024m
              memory: 800Mi
            limits:
              cpu: 2048m
              memory: 1200Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initalDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThshold: 3
          readinressProbe:
            tcpSocket:
              port: 8080
            initalDelaySeconds: 15
            periodSeconds: 10
            successThshold: 2
            failureThshold: 3
      volumes:
        - name: user-configmap
          configmap:
            secretName: user-service
        - name: user-secret
          secret:
            secretName: user-service

