apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: backend
  labels:
    app: user
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: metrics
  type: ClusterIP
